title: Can Beets Turn Poop Red Or Am I Dying?
email: your-email@domain.com
description: Is your poop red? Ate some beets? Want to know if you're dying? This is the place for you.
url: "http://canbeetsturnpoopredoramidying.com/"
logo: "android-chrome-192x192.png"
google_analytics: ""
# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
